### ISSUE TITLE
Some errors are not caught and returned as such

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraJS#2]
For instance, getting a feed will not reject the Promise in case of an error. Also, there is no way to obtain the error message returned by the server.

Example:
```
Mura.getFeed('contact').getQuery().then((contactCollection) => {
// will be here when an error occurs
}, (request) => {
// should be here with an error message
});

```
Partial workaround: in this case, check if there is an 'items' property on the returned collection:
`contactCollection.get('items')
`

**Comment by mattlevine** [comment]
Please update your Mura core and MuraJS and retest.
