### ISSUE TITLE
userBean.exists() false when the user exists

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraJS#3]
The `isnew` property is set to 1 after loading a Mura user that does exist (this is actually set by the Mura 7 server, not MuraJS). As a result, `exists()` returns false and `getIsNew()` returns true.

Example:
```
Mura.getBean('user').loadBy('email', email).then((userBean) => {
// userBean.exists() is always false

```

**Comment by mattlevine** [comment]
If you update your core this should be fixed.
