### ISSUE TITLE
Recent change from _cacheid to cacheid breaks API calls

### ISSUE THREAD

**Issue by altitudems** [blueriver/MuraJS#6]
Recently @mattlevine updated the query parameter for cache busting to `cacheid` from `_cacheid`.

This seems to have broken the API for Mura (7.1.249). There are no errors but no items are returned.

This works:
http://localhost:8001/index.cfm/_api/json/v1/default/content/?_cacheid=0.250024203399607sd&pageIndex=0

This does not:
http://localhost:8001/index.cfm/_api/json/v1/default/content/?cacheid=0.250024203399607sd&pageIndex=0

**Comment by mattlevine** [comment]
I believe that you ran into this issue because you were using a Mura.js version newer than you Mura core version.  However, it points out a real issue, so I rolled it back.
